Improve test
alejandron00/protractor-workshop-2020 pull request #2
Opened 2020-07-30 14:04 UTC by alejandron00

2020-07-30 14:27 UTC, holgiosalos approved these changes

2020-07-30 14:27 UTC, holgiosalos requested changes
Please fix the merge conflicts

2020-07-30 14:30 UTC, leonleo997 commented on package.json
> +    "protractor": "^7.0.0"
move as a dev dependency `npm install -D protractor`

2020-07-30 14:51 UTC, holgiosalos commented on package.json
> -    "typescript": "^3.9.7"
please do not remove typescript from dev-depedencies

2020-07-31 13:31 UTC, holgiosalos approved these changes

2020-07-31 13:32 UTC, merged